/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MessageBoard } from "./MessageBoard";
export * as factories from "./factories";
export { MessageBoard__factory } from "./factories/MessageBoard__factory";
